version: '2'
services:
  front:
    build: ./front
    ports:
      - "4001:4001"
  backend:
    image: chattingroom-backend
    ports:
      - "4000:4000"
  redis:
    image: redis
    ports: 
      - "6379:6379"
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
