version: '2'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_USER: root  
      MYSQL_PASSWORD: "123456"  
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - my-datavolume:/var/lib/mysql  

  backend:
    image: chattingroom-backend
    ports:
      - "4000:4000"

  front:
    image: front
    ports:
      - "4001:4001"