version: '2'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  mysql:
    image: mysql
    ports: 
      - "3306:3306"

  backend:
    image: chattingroom-backend
    links:
      - mysql: mysql
    ports:
      - "4000:4000"

  front:
    image: front
    ports:
      - "4001:4001"
