version: '2'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  backend:
    image: chattingroom-backend
    ports:
      - "4000:4000"

  front:
    image: front
    ports:
      - "4001:80"
