version: '2'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  mysql:
    image: mysql
    expose:
      - "3306"
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: 'chattingroom'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'

  backend:
    image: chattingroom-backend
    ports:
      - "4000:4000"

  front:
    image: front
    ports:
      - "4001:4001"
